CREATE DATABASE CLUB_REGISTRATION;
USE CLUB_REGISTRATION;

CREATE TABLE LECT_ADVISOR(
Lect_ID VARCHAR(35) NOT NULL,
Lect_Name VARCHAR(100),
Lect_No INTEGER,
Lect_Faculty VARCHAR(100),
PRIMARY KEY (Lect_ID));

CREATE TABLE CLUB_LEADER(
Leader_ID VARCHAR(35) NOT NULL,
Leader_Name VARCHAR(100),
Leader_Role VARCHAR(50),
Lect_ID VARCHAR(35),
PRIMARY KEY (Leader_ID),
FOREIGN KEY(Lect_ID) REFERENCES LECT_ADVISOR(Lect_ID));

CREATE TABLE STUDENT(
Stu_ID VARCHAR(35) NOT NULL,
Stu_Name VARCHAR(100),
Stu_Program VARCHAR(50),
Stu_Faculty VARCHAR(35),
Stu_No INTEGER,
Leader_ID VARCHAR(35),
PRIMARY KEY(stu_ID),
FOREIGN KEY(Leader_ID) REFERENCES CLUB_LEADER (Leader_ID));

CREATE TABLE CLUB(
Club_ID VARCHAR(35) NOT NULL,
Club_Name VARCHAR(100),
Club_Location VARCHAR(225),
Club_Desc VARCHAR (225),
PRIMARY KEY(Club_ID));

CREATE TABLE REGISTRATION(
Register_ID VARCHAR(35) NOT NULL,
Register_status VARCHAR(35),
Register_Date DATE,
Stu_ID VARCHAR(35),
Lect_ID VARCHAR(35),
Club_ID VARCHAR(35),
PRIMARY KEY(Register_ID),
FOREIGN KEY(Stu_ID) REFERENCES STUDENT (Stu_ID),
FOREIGN KEY(Lect_ID) REFERENCES LECT_ADVISOR (Lect_ID),
FOREIGN KEY(Club_ID) REFERENCES CLUB (Club_ID));

commit;


